### ISSUE TITLE
implementation is not thread-safe

### ISSUE THREAD

**Issue by educhastenier** [Bonitasoft-Community/filter_remoteAddr#1]
To the contrary to what you say in the comments, you don't make a thread-safe copy, you just point to the instance variable, which is **not** thread-safe:
https://github.com/Bonitasoft-Community/filter_remoteAddr/blob/8563ffa5b4d1a0da18f5aa2821533c829480729b/src/org/bonitasoft/filter/allowed/FilterRemoteAddr.java#L87

**Comment by pierre-yves-monnet** [comment]
Hello,
I totally agree with your comment. I just copy the  org.apache.catalina.valves.RequestFilterValve.java and I didn't understand it because
   Pattern deny = this.deny;
     is not a clone() but a reference.

I checked the Pattern.matcher() and according to stackoverflow (https://stackoverflow.com/questions/1360113/is-java-regex-thread-safe?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) it's correclty thread safe, so let's update that.
